version: "3.7"

x-database-variables: &database-variables
  POSTGRES_DB: ${DB_NAME}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  POSTGRES_USER: ${DB_USERNAME}

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment: *database-variables
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: