name: RPG API CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: export JAVA_HOME=$JAVA_HOME_17_X64 && mvn -B clean package -DskipTests --file pom.xml

  format:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Run checkstyle
        run: export JAVA_HOME=$JAVA_HOME_17_X64 && mvn checkstyle:check --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Bring up DB
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--remove-orphans"
          down-flags: "--remove-orphans"
          services: |
            test-postgres
      - name: Run tests
        run: export JAVA_HOME=$JAVA_HOME_17_X64 && mvn test --file pom.xml
